---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1uegnd6s4nkq66l4t55x5m8t2sc9su8pjvc69n4hcnye68rka44jqqs700h"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1uegnd6s4nkq66l4t55x5m8t2sc9su8pjvc69n4hcnye68rka44jqqs700h"
