---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  BOOTSTRAP_DIR: '{{.ROOT_DIR}}/bootstrap'
  KUBERNETES_DIR: '{{.ROOT_DIR}}/kubernetes'
  SCRIPTS_DIR: '{{.ROOT_DIR}}/scripts'
  BOOTSTRAP_CONFIG_FILE: '{{.ROOT_DIR}}/config.yaml'
  MAKEJINJA_CONFIG_FILE: '{{.ROOT_DIR}}/makejinja.toml'
  SOPS_CONFIG_FILE: '{{.ROOT_DIR}}/.sops.yaml'

dotenv: ['.1p.env']

env:
  KUBECONFIG: '{{.ROOT_DIR}}/kubeconfig'
  PYTHONDONTWRITEBYTECODE: '1'
  SOPS_AGE_KEY_FILE: '{{.ROOT_DIR}}/age.key'
  VIRTUAL_ENV: '{{.ROOT_DIR}}/.venv'

includes:
  bootstrap: .taskfiles/bootstrap
  kubernetes: .taskfiles/kubernetes
  talos: .taskfiles/talos
  workstation: .taskfiles/workstation
  user:
    taskfile: .taskfiles/user
    optional: true

tasks:

  default: task --list

  validate:
    internal: true
    cmds:
      - task: kubernetes:kubeconform
      - cmd: echo === Done rendering and validating YAML ===
      - cmd: |
          if test -f ~/.config/sops/age/keys.txt; then
            echo WARNING: SOPS Age key found in home directory, this may cause conflicts.
          fi
    silent: true
