apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:4aOJtXeAV0IUiD/vqzC3W+LhxJIeonGwcDLr2YDd97xsDSav,iv:sqNUinoM/9E9rMvm8YOou5ofXwMXjENdGm69Yb3RDAw=,tag:bMjhOW21FTFNK6CqdiONHQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:5H++9oOKPLpg/xa4wBL9EP7dL/c3Bt3OYFo9YV7ABPRoFHn523c+HFxPfrU7feYCn3BccK2dLXssbKW5U3P83J7zUFwXqhJ6CK+dz4ScNlCEDaopI7/1P/Qxvg1XmXBXuIDNNekhgc5FVAjZZwwBjVsM/MP8fpNZ4c5b4MVDT9Esr0nT6r0YcNx35bKNFG7/wzOsQssUFLtHHElH40iRYt19WvyXIgpGGPxODJpb4A==,iv:gDTvkpfVHkPPlD8pRh0qMwfgWeJcr6hJZsFVkO0rAxQ=,tag:8ShzTQyeRHAzgk/SvidPHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uegnd6s4nkq66l4t55x5m8t2sc9su8pjvc69n4hcnye68rka44jqqs700h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3b1dUWVJUbkFBMXFXMDZl
            d1VZc0x6QjJ0c2thTWdQRTNScFIxdnNoTEQwCmlkRGIxdDliNnV2RkZySmNTYWZs
            UDlIWTQ3RkY1Z09DZUV5UGlBQVU0RnMKLS0tIFFndjUyMXk2VFkyTDQzUVliRjVl
            a05MeTR2NjZoMmxMSFhCcWdxMCtWbmMKviCu7D+0qUEbOkIegRWeiyox9qovDSZD
            1kcSz2nrI/3WdrcapOHnQc51Q4rSaN7eqRJwH+zlIPevOd8FBvHgug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-02T05:38:01Z"
    mac: ENC[AES256_GCM,data:3VUIA9xHt9qdPPC/xCCtWgoBbLlqmTvsr6SjiXWlbMDwsBRdwdtHIDfW0MNNPdg6z5zPURMgCD2nxesFaUhzSSfLSBdQ7K8jpGhAFBGFwkU8RoZ/HXjLEOnwpQSqnd6HD+Dq23c2bs7heBJGOwQU1BjTr+EFl5t4lGAXF4JWfY8=,iv:ad03lmSUTmHb+QmG12/Ogcarn3yEa1jPrPLf+ks26Cg=,tag:Spbryx+7o5kApEmk3tlepg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
