apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:ESguEuyCthBPZJD30KUrPRggwcOsv99t/MY3aDv8gFc=,iv:kgfVYG5ahCwgKiE0wdmKHtt0rTyjQbz3GN1X/WUw1/4=,tag:n1PTiWBt+hqgpxSpu3m0AA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uegnd6s4nkq66l4t55x5m8t2sc9su8pjvc69n4hcnye68rka44jqqs700h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUWZTUmlSbmJnTmV0MWE2
            citDVTJOcmtyYzRSQmRKanI2TEsyUkVxSG1NCjNaTGJGZFltV0J0c1cvblJFL3Mx
            S3dCNERnYkZJMEloY2prR0dWNmJKbmMKLS0tIFVrTjNPZmk5ZWdialhWL0gzRXZV
            VGdEUVc5Rndib0dhL1EvMThhMTFhWXcKBz/Vb0oUJq+eYLf6ZabBUo07glaboX1i
            RHdfjrJlqXJoXWj12yVLYBho5fNtKK9Twbak9ypCo2um7+O7g4BEpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-02T05:38:01Z"
    mac: ENC[AES256_GCM,data:vQBWCKrRB0EE+zSA4ZMU6jZSSr+b1ecVjOCcXISKTiivu5zDOFf3fC5FPQr/cwe9itEqH7ySPbVAHV6BZUTO1tKrCpdHPjeHVshNwEVpZems1821Wg+4vj9moiwRSRCeJK0J+9rLUbXr6jLP7lVg9HGWeOR4A0WKZJ1r/15tOrI=,iv:3/+GLleimyMdnJMDoWPYn9JTlu6FEFS53H4j4dGTQ/c=,tag:JQ5X68kdcbjivUhU0PnM8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
