apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:R3ZvYpwybgGEudB2sW4A/dpmv5z591Pk7JhIxgmlpTb08H/L096jDA==,iv:wBLe5O77DHb//5foSfxUxtteJ/uqxVJUSQK1HA6SQoM=,tag:5zDcARoSZwp5cOClFzNUnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uegnd6s4nkq66l4t55x5m8t2sc9su8pjvc69n4hcnye68rka44jqqs700h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISkxKSDVXUTYzR3hOeE1a
            SXlEdEpUMzMrWDFtZk1aK2lMbHgybVg0SXcwCjdLcDBkSFozUFNmcUJuVG4zcTZp
            eXFDYngrRkNHSGlMQlhaYkdQekl6VTAKLS0tIGlmNGlROHJDdXZCRUFxSG5aeFh0
            eHhTVnIycUNGQW1pQmtoQTVxSytHQncK5ksZpwB4n1iT5bHebI/HrWnLumGngdLO
            8GusRNuKvZb1Ev02YsbbA6xyYvBcuYixWCiulHIC3WnyPOPx7ix7/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-30T05:05:25Z"
    mac: ENC[AES256_GCM,data:sFrN2VtXmJNJOa+iWqGObPPfSFLFHXbtPA3MGzZi02uRrKxR5MTtaOliiP7oRz6L4I4hqWvSzVaGAAwzmgwTMg3uoZ7mc7D4HfHGZnN2y+agsyQMi1FBoVAEMMHNOzrVGHaV1Zmb86hOwy6TaZiXJVwDHa7UO48S1BhMixoC0sY=,iv:mD8JvUk0AjKFYqqclEFhf6AilZLLUR53bL5ja9GdtRw=,tag:LUG6P4ini/H+U6TRy+mFPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
